//installed packages
export {default as Modal} from '@material-tailwind/react/Modal'
export {default as ModalHeader} from '@material-tailwind/react/ModalHeader'
export {default as ModalBody} from '@material-tailwind/react/ModalBody'
export {default as ModalFooter} from '@material-tailwind/react/ModalFooter'
export {default as Button} from '@material-tailwind/react/Button'
export {default as Icon} from '@material-tailwind/react/Icon'
export {default as Tab} from '@material-tailwind/react/Tab'
export {default as TabItem} from '@material-tailwind/react/TabItem'
export {default as TabContent} from '@material-tailwind/react/TabContent'
export {default as TabList} from '@material-tailwind/react/TabList'
export {default as TabPane} from '@material-tailwind/react/TabPane' 
export {BsInfoLg, BsHddNetwork} from 'react-icons/bs'
export {BiSolidSchool} from 'react-icons/bi'
export {FcAcceptDatabase} from 'react-icons/fc'
export {FaConnectdevelop} from 'react-icons/fa'
export {SiBmcsoftware} from 'react-icons/si'
export {AiOutlineHome} from 'react-icons/ai'
//local components
export {default as DIHeader} from './for-desktop/header/DesktopIndHeader'
export {default as MIHeader} from './for-mobile/header/MobileIndHeader'
export {default as DesktopIndex} from './for-desktop/body/desktop-index/DesktopIndex'
export {default as CourseCard} from './for-desktop/body/course-card/CourseCard'
export {default as course_card} from '../data/course_card.json'
export {default as courses} from '../data/courses.json'
export {default as jobs} from '../data/jobs.json'
export {default as ReviewCard} from './for-desktop/body/review-card/ReviewCard'
export {default as reviews} from '../data/reviews.json'
export {default as CDHeader} from './for-desktop/header/cyber_header/CyberHeader'
export {default as CMHeader} from './for-mobile/header/cyber_header/CyberHeader'
export {default as LongerCard} from './for-desktop/body/course-card/LongerCard'
export {default as FEDHeader} from './for-desktop/header/frontend_header/FrontEndHeader'
export {default as FEMHeader} from './for-mobile/header/frontend_header/FrontEndHeader'
export {default as BEDHeader} from './for-desktop/header/backend_header/BackEndHeader'
export {default as BEMHeader} from './for-mobile/header/backend_header/BackEndHeader'
export {default as DSDHeader} from './for-desktop/header/datasci_header/DataSciHeader'
export {default as DSMHeader} from './for-mobile/header/datasci_header/DataSciHeader'
export {default as PMDHeader} from './for-desktop/header/projman_header/ProjManHeader'
export {default as PMMHeader} from './for-mobile/header/projman_header/ProjManHeader'
export {default as SEDHeader} from'./for-desktop/header/se_header/SEHeader'
export {default as SEMHeader} from './for-mobile/header/se_header/SEHeader'
export {default as UXDHeader} from './for-desktop/header/ux_header/UXHeader'
export {default as UXMHeader} from './for-mobile/header/ux_header/UXHeader'
export {default as CourseHeader} from './for-desktop/header/CourseHeader'
export {default as MobCourseHeader} from './for-mobile/header/CourseHeader'
export {default as ShortCard} from './for-desktop/body/short-card/ShortCard'
export {default as DeskJobHeader} from './for-desktop/header/JobsHeader'
export {default as MobJobHeader} from './for-mobile/header/JobsHeader'
export {default as JobCard} from './for-desktop/body/job-card/JobCard'
export {default as MobJob} from './for-mobile/body/job-card/JobCard'
export {default as DeskSuppHeader} from './for-desktop/header/SuppHeader'
export {default as MobSuppHeader} from './for-mobile/SuppHeader'
export {default as SupportRoutes} from './for-mobile/SuppHeadRoutes'